[package]
name = "YAM"
version = "0.0.1"
edition = "2021"

[dependencies]
# graph database
indradb-lib = { version = "*", features = ["rocksdb-datastore"] }
# managin yaml documents
yaml-rust2 = { version = "0.8" }
